### ISSUE TITLE
Channel logs end on `2017-02-05`

### ISSUE THREAD

**Issue by menelaos** [chrisdone/ircbrowse#25]
There seems to be a problem with www.ircbrowse.net. 
Browsing and searching the chat history is only possible up to around `2017-02-05T18:40`.

**Comment by chrisdone** [comment]
I'm currently migrating it to another host. The logging database is up to date, but the web site is still looking at the old host. It'll be moved to the new one soon.

**Comment by chrisdone** [comment]
Some movement on this. Basically the logging system got stuck when znc changed its file format and directory locations. Since then I haven't been interested in trudging through updating that and getting the logger unstuck.  

I've inserted some duct tape to get the process on the way again. The import process is very slow on this server, and the service is regularly hit by botnets, which impede the database's abilities. So I'm taking the site down while this goes through.

**Comment by Hexstream** [comment]
`the service is regularly hit by botnets, which impede the database's abilities.`

Wouldn't moving behind a CDN greatly help with this kind of stuff?

[Cloudflare](https://www.cloudflare.com/) is particularly easy to setup, and free for your use-case (sensical HTTPS is not free, but you're currently HTTP-only anyway).

**Comment by chrisdone** [comment]
It could do. There are about 4 million pages, so it would depend on CloudFlare and also whether botnets request random URLs in which case it would be a cache miss more than likely. Worth considering, though.

**Comment by chrisdone** [comment]
This is working. The logs are being added one day per hour. Closing.

**Comment by Hexstream** [comment]
The more popular content at any point in time is likely only a small subset of the 4 million pages, and since it's just text, if you specify super long expiration times (at least a month) I think that's going to be honored and a lot of the content people actually access should get cached pretty effectively.

Besides, there are many advantages to using Cloudflare (or CDNs in general) even if, theoretically, 100% of your requests were cache misses. (Low-level DDoS attack protection comes to mind.)

These days, my opinion is that most websites (even "insignificant" ones) should go behind a CDN as a matter of course, since it's dirt cheap (and easy to setup) at the entry level. I've used both CloudFront and Cloudflare, and they're pretty great. I wish I could just migrate everything to Cloudflare but they don't yet have *good* free SSL/TLS certificates. Right now, 100% of my sites are behind a CDN and are HTTPS-only. :)

Anyway, just my 2¢. Thanks for fixing.

**Comment by chrisdone** [comment]
It's not about popular content, a botnet's purpose is generally requesting random content, as far as I've seen. If I'm requesting random URLs, then they will all hit the server, because CloudFlare won't have it in cache.

However, some more delving into the issue seems to be that the traffic from the botnets wasn't actually a factor (in retrospect is obvious, as I made the queries really optimized), but rather that on this smaller machine (than the old one), the cronjob takes 40 minutes instead of 1 minute, so the per-minute cronjob overloaded the PostgreSQL server and naturally ground to a halt. I just realized that today. I've changed the cronjob to hourly.

Cloudflare is good, I'm using it for https://tryhaskell.org/
