### ISSUE TITLE
libpq: failed (another command is already in progress)

### ISSUE THREAD

**Issue by cyrbon** [chrisdone/ircbrowse#27]
For the past few days or even weeks IrcBrowse seems to be unavailable due to this error:

```
A web handler threw an exception. Details:
libpq: failed (another command is already in progress
)
```

**Comment by 23Skidoo** [comment]
/cc:ing @chrisdone just in case he missed this.

**Comment by Hexstream** [comment]
http://ircbrowse.net/browse/lisp is an example of a failing link.

I deem this an important service in the Common Lisp community and would love to see it back to working order.

(I've already contacted you on twitter about it, I hope this message won't be seen as too redundant.)

**Comment by 23Skidoo** [comment]
Looks like this is fixed now, but there are no logs newer than 2017-02-05 (#25). The bot seems to be up at least.

**Comment by chrisdone** [comment]
Actually it seems that I may have simply miscalculated, after moving to a new server, that while serving up the page is fast, actually my cron job to update the database from the logs takes about 40 minutes on this smaller machine, than the <1 minute or so that it took on my Hezner dedicated host. So I believe they ended up overlapping and creating a complete deadlock. 

I've changed this cronjob to be hourly instead of per minute. The logs are updating and the server seems OK for now. I'll keep an eye on it.

**Comment by 23Skidoo** [comment]
Oh noes! It's [back](http://ircbrowse.net/browse/hackage)!
